#!/bin/bash

# Variables for MySQL login credentials
MYSQL_USER="root"
MYSQL_PASSWORD="Passw0rd"

# Commands to create databases, users, and grant privileges
MYSQL_COMMANDS="
CREATE DATABASE hive DEFAULT CHARACTER SET utf8;
CREATE USER 'hive'@'%' IDENTIFIED BY 'P@ssw0rd';
GRANT ALL ON hive.* TO 'hive'@'%';

CREATE DATABASE hue DEFAULT CHARACTER SET utf8;
CREATE USER 'hue'@'%' IDENTIFIED BY 'P@ssw0rd';
GRANT ALL ON hue.* TO 'hue'@'%';

CREATE DATABASE rman DEFAULT CHARACTER SET utf8;
CREATE USER 'rman'@'%' IDENTIFIED BY 'P@ssw0rd';
GRANT ALL ON rman.* TO 'rman'@'%';

CREATE DATABASE oozie DEFAULT CHARACTER SET utf8;
CREATE USER 'oozie'@'%' IDENTIFIED BY 'P@ssw0rd';
GRANT ALL ON oozie.* TO 'oozie'@'%';

CREATE DATABASE navs DEFAULT CHARACTER SET utf8;
CREATE USER 'navs'@'%' IDENTIFIED BY 'P@ssw0rd';
GRANT ALL ON navs.* TO 'navs'@'%';

CREATE DATABASE navms DEFAULT CHARACTER SET utf8;
CREATE USER 'navms'@'%' IDENTIFIED BY 'P@ssw0rd';
GRANT ALL ON navms.* TO 'navms'@'%';

CREATE DATABASE actmo DEFAULT CHARACTER SET utf8;
CREATE USER 'actmo'@'%' IDENTIFIED BY 'P@ssw0rd';
GRANT ALL ON actmo.* TO 'actmo'@'%';

CREATE DATABASE sentry DEFAULT CHARACTER SET utf8;
CREATE USER 'sentry'@'%' IDENTIFIED BY 'P@ssw0rd';
GRANT ALL ON sentry.* TO 'sentry'@'%';

CREATE USER 'temp'@'%' IDENTIFIED BY 'P@ssw0rd';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO 'temp'@'%' WITH GRANT OPTION;
"

# Run MySQL commands
mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "$MYSQL_COMMANDS"

# Exit the script
exit 0

